
package com.example.springwsclient.jaxb;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "productActionService", targetNamespace = "http://www.sample.com/schemas", wsdlLocation = "wsdl/product.wsdl")
public class ProductActionService
    extends Service
{

    private final static URL PRODUCTACTIONSERVICE_WSDL_LOCATION;
    private final static WebServiceException PRODUCTACTIONSERVICE_EXCEPTION;
    private final static QName PRODUCTACTIONSERVICE_QNAME = new QName("http://www.sample.com/schemas", "productActionService");

    static {
        PRODUCTACTIONSERVICE_WSDL_LOCATION = ProductActionService.class.getResource("wsdl/product.wsdl");
        WebServiceException e = null;
        if (PRODUCTACTIONSERVICE_WSDL_LOCATION == null) {
            e = new WebServiceException("Cannot find 'wsdl/product.wsdl' wsdl. Place the resource correctly in the classpath.");
        }
        PRODUCTACTIONSERVICE_EXCEPTION = e;
    }

    public ProductActionService() {
        super(__getWsdlLocation(), PRODUCTACTIONSERVICE_QNAME);
    }

    public ProductActionService(WebServiceFeature... features) {
        super(__getWsdlLocation(), PRODUCTACTIONSERVICE_QNAME, features);
    }

    public ProductActionService(URL wsdlLocation) {
        super(wsdlLocation, PRODUCTACTIONSERVICE_QNAME);
    }

    public ProductActionService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, PRODUCTACTIONSERVICE_QNAME, features);
    }

    public ProductActionService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public ProductActionService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns ProductAction
     */
    @WebEndpoint(name = "productActionSoap11")
    public ProductAction getProductActionSoap11() {
        return super.getPort(new QName("http://www.sample.com/schemas", "productActionSoap11"), ProductAction.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns ProductAction
     */
    @WebEndpoint(name = "productActionSoap11")
    public ProductAction getProductActionSoap11(WebServiceFeature... features) {
        return super.getPort(new QName("http://www.sample.com/schemas", "productActionSoap11"), ProductAction.class, features);
    }

    private static URL __getWsdlLocation() {
        if (PRODUCTACTIONSERVICE_EXCEPTION!= null) {
            throw PRODUCTACTIONSERVICE_EXCEPTION;
        }
        return PRODUCTACTIONSERVICE_WSDL_LOCATION;
    }

}
